pipeline {
  agent any

  tools {
    jdk 'Java17'
    maven 'Maven'
  }

  environment {
    PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    DOCKERHUB_USER = "saniidhya24"
    IMAGE_NAME = "saniidhya24/indiaproj"
    IMAGE_TAG = "latest"
  }

  stages {

    stage('Checkout Code') {
      steps {
        echo 'Pulling from Github'
        git branch: 'main',
            credentialsId: 'mygithubcred',
            url: 'https://github.com/SanidhyaAulakh/k8test.git'
      }
    }

    stage('Build Project') {
      steps {
        echo 'Building Spring Boot project'
        sh '''
          cd indiaproj
          mvn clean package -DskipTests
        '''
      }
    }

    stage('Build Docker Image') {
      steps {
        echo 'Building Docker Image'
        sh '''
          cd indiaproj
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
        '''
      }
    }

    stage('Push Docker Image to DockerHub') {
      steps {
        echo 'Pushing Docker Image'
        withCredentials([string(credentialsId: 'dockerhubpwd', variable: 'DOCKER_PASS')]) {
          sh '''
            echo "$DOCKER_PASS" | docker login -u saniidhya24 --password-stdin
            docker push saniidhya24/indiaproj:latest
          '''
        }
      }
    }

    stage('Deploy to Minikube (K8s)') {
      steps {
        echo 'Deploying to Kubernetes'
        sh '''
          minikube start
          minikube image load ${IMAGE_NAME}:${IMAGE_TAG}

          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

          kubectl get pods
          kubectl get svc
        '''
      }
    }
  }

  post {
    success {
      echo 'BUILD + DOCKER + K8s DEPLOY SUCCESSFUL!'
    }
    failure {
      echo 'OOPS!!! Failure.'
    }
  }
}